<?php

/**
 * @file
 * Install, update and uninstall functions for the bbs_base module.
 */

/**
 * Implements hook_install().
 */
function bbs_base_install() {
    bbs_base_set_theme();
    bbs_base_set_frontpage();
}

function bbs_base_set_frontpage() {
  variable_set('site_frontpage', 'bbs_frontpage');
}

function bbs_base_set_theme() {
  $themes = list_themes();
  if ($themes['bbs']->status == 0) {
      theme_enable(array('bbs')); 
  }
  variable_set('default_theme', 'bbs');
}