<?php

/**
 * @file
 * Ting search carousel module main file.
 */


/**
 * Implements hook_block_info().
 */
function bbs_event_carousel_block_info() {
  return array(
    'bbs_event_carousel' => array(
      'info' => 'BBS Event carousel',
    ),
  );
}

/**
 * Implements hook_block_view().
 *
 * We ignore delta in this block view, as we only have one block.
 */
function bbs_event_carousel_block_view($delta) {
    $view_names = array('frontpage_events_1', 'frontpage_events_2');
    $carousels = array();
    $block = new stdClass();
    foreach($view_names as $view_name) {
        $title = views_get_view($view_name)->get_title();
        $items = views_get_view_result($view_name, 'block');
        $result = array();
        foreach($items as $item) {
            $node = node_load($item->nid);
            $view = node_view($node, 'teaser');
            $result[] = drupal_render($view);
        }

        $carousels[] = array(
            '#type' => 'ding_carousel',
            '#title' => $title,
            '#items' => $result,
            '#offset' => -1,
        );
    }

    $block->content = array(
        '#type' => 'ding_tabbed_carousel',
        '#tabs' => $carousels,
        '#transition' => 'fade',
    );

    return $block;
}

