<?php

/**
 * @file
 * Ting search carousel module main file.
 */

/**
 * Implements hook_menu().
 */
function bbs_color_block_menu() {
    $items = array();

    return $items;
}

/**
 * Implements hook_permission().
 */
function bbs_color_block_permission() {
    return array(
        'configure carousel' => array(
            'title' => t('Configure carousel'),
            'description' => t('Allow role to configure carousel.'),
        ),
    );
}

/**
 * Implements hook_theme().
 */
function bbs_color_block_theme($existing, $type, $theme, $path) {
    return array(
        'bbs_color_block_admin_form' => array(
            'render element' => 'form',
        ),
    );
}

/**
 * Implements hook_block_info().
 */
function bbs_color_block_block_info() {
    return array(
        'bbs_color_block' => array(
            'info' => 'BBS Color Block',
        ),
    );
}

/**
 * Implements hook_block_view().
 *
 * We ignore delta in this block view, as we only have one block.
 */
function bbs_color_block_block_view($delta) {
    return array(
        'content' => theme('bbs_color_block', array(
        )),
    );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function bbs_color_block_ctools_plugin_directory($module, $plugin) {
    if ($module == 'ctools' || $module == 'panels') {
        return 'plugins/' . $plugin;
    }
}

/**
/**
 * Implements hook_image_default_styles().
 */
function bbs_color_block_image_default_styles() {
    return array(
        'bbs_color_block' => array(
            'name' => 'bbs_color_block',
            'effects' => array(
                array(
                    'label' => 'Scale and crop',
                    'effect callback' => 'image_scale_and_crop_effect',
                    'dimensions callback' => 'image_resize_dimensions',
                    'module' => 'image',
                    'name' => 'image_scale_and_crop',
                    'data' => array(
                        'width' => '200',
                        'height' => '290',
                    ),
                    'weight' => '1',
                ),
            ),
        ),
    );
}


function theme_bbs_color_block_admin_form(array $variables) {
    $form = $variables['form'];

    $header = array('Searches', '');
    $rows = array();

    $table_vars = array(
        'header' => $header,
        'rows' => $rows,
        'attributes' => array('id' => 'ting-search-carousel-admin-sort'),
        'caption' => '',
        'colgroups' => array(),
        'sticky' => FALSE,
        'empty' => 'EMPTY',
    );
    $output = theme('table', $table_vars);

    // Render remaining elements.
    $output .= drupal_render_children($form);

    return $output;
}
