<?php

/**
 * Implementation of hook_views_api()
 */
function bbs_frontpage_views_api() {
    return array('api' => 3.0);
}

/**
 * Implements hook_ctools_plugin_api().
 */
function bbs_frontpage_ctools_plugin_api($module, $api) {
    if ($module == 'quicktabs' && $api == 'quicktabs') {
        return array(
            'version' => '1',
            'path' => drupal_get_path('module', 'bbs_frontpage') . '/quicktabs'
        );
    }
}
