<?php

/**
 * @file
 * Install, update and uninstall functions for the ding_innskraning module.
 */

/**
 * Implements hook_install().
 */
function ding_innskraning_install() {
  // Needed by ding_innskraning_form_profile2_form_alter() to ensure it's called
  // after ding_user_form_profile2_form_alter().
  db_update('system')
    ->fields(array(
      'weight' => 100,
    ))
    ->condition('name', 'ding_innskraning')
    ->execute();
}
